services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
  api:
    image: "ghcr.io/lucasnetwork/counter:main"
    deploy:
      replicas: 3
      endpoint_mode: vip
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    labels:
      traefik.http.routers.client.rule: "PathPrefix(`/`)"
      traefik.enable: true
      com.centurylinklabs.watchtower.enable: true
  reverse-proxy:
    image: traefik:v3.3
    command: 
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=false"
    ports:
      - "80:80"
      - "8080:8080"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.users=admin:$apr1$zyNmSGbG$hwlUaZlOHoIpHnx3.FL9N0"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
networks:
  traefik_webgateway:
    driver: bridge
